const fs = require('fs');
const path = require('path');

function removeHorizontalLines(filePath) {
   let content = fs.readFileSync(filePath, 'utf8');

   // Remove the common border dividing parts inside components
   content = content.replace(/border-t border-border-main/g, '');
   content = content.replace(/border-b border-border-main/g, '');
   content = content.replace(/border-l border-border-main/g, '');
   content = content.replace(/border-r border-border-main/g, '');
   
   // Clean up any double spaces generated by removing classes
   content = content.replace(/  +/g, ' ');

   fs.writeFileSync(filePath, content, 'utf8');
}

function traverseDir(dir) {
   const files = fs.readdirSync(dir);
   for (const file of files) {
      const fullPath = path.join(dir, file);
      if (fs.statSync(fullPath).isDirectory()) {
         // do nothing
      } else if (file.startsWith('Academy') && fullPath.endsWith('.tsx')) {
         removeHorizontalLines(fullPath);
      }
   }
}

traverseDir(path.join(process.cwd(), 'src/pages'));
console.log('Removed inner lines!');
